lithops: 
    #storage: ibm_cos
    storage_bucket: <BUCKET_NAME>
    #executor: serverless
    #rabbitmq_monitor: <True/False>
    #data_cleaner: <True/False>
    #workers: <MAX_NUM_OF_WORKERS>
    #data_limit: 4  # in MiB
    #execution_timeout: 1800
    #include_modules: <LIST_OF_MODULES>
    #exclude_modules: <LIST_OF_MODULES>

#serverless:
    #backend: ibm_cf
    #runtime : <RUNTIME_NAME>
    #runtime_timeout: 600
    #runtime_memory: 256
    #remote_invoker: <True/False>

#standalone:
    #backend: ibm_vpc
    #runtime: <RUNTIME_NAME>
    #auto_dismantle: True
    #hard_dismantle_timeout: 3600
    #soft_dismantle_timeout: 300

#ibm:
   #iam_api_key: <IAM KEY>

#ibm_cf:
    #endpoint    : <REGION_ENDPOINT>
    #namespace   : <NAMESPACE>
    #api_key     : <API_KEY>
    #namespace_id : <NAMESPACE_ID> # Only for IAM auth

#code_engine:
    #kubectl_config: <Location for kubectl yaml file>

#ibm_cos:
    #endpoint    : <REGION_ENDPOINT>
    #private_endpoint: <PRIVATE_REGION_ENDPOINT>
    #api_key     : <API_KEY>
    #access_key : <ACCESS_KEY>  # Optional
    #secret_key : <SECRET_KEY>  # Optional

#ibm_vpc:
    #endpoint    : <REGION_ENDPOINT>
    #instance_id : <INSTANCE_ID>
    #ip_address  : <FLOATING_IP_ADDRESS>
    #version     : <VPC_VERSION>
    #generation  : <VPC_GENERATION>
    #ssh_user    : <SSH_USERNAME>
    #ssh_key_filename: <SSH_PASSWORD>

#vm:
    #host: <IP_ADDRESS>
    #ssh_user: <SSH_USERNAME>
    #ssh_password: <SSH_PASSWORD>

#rabbitmq:
    #amqp_url   : <RABBIT_AMQP_URL>  # amqp://

#knative:
   #istio_endpoint  : <ISTIO_INGRESS_ENDPOINT>
   #docker_user     : <DOCKER_HUB_USERNAME>
   #docker_token    : <DOCKER_HUB_TOKEN>

#docker:
    #host: <HOST_IP>
    #ssh_user: <SSH_USER>
    #ssh_password: <SSH_PASSWORD>

#openwhisk:
    #endpoint    : <OW_ENDPOINT>
    #namespace   : <NAMESPACE>
    #api_key     : <AUTH_KEY>
    #insecure    : <True/False>

#swift:
    #auth_url   : <SWIFT_AUTH_URL>
    #region     : <SWIFT_REGION>
    #user_id    : <SWIFT_USER_ID>
    #project_id : <SWIFT_PROJECT_ID>
    #password   : <SWIFT_PASSWORD>

#infinispan:
    #username   : <USER_NAME>
    #password   : <PASSWORD>
    #endpoint   : <INFINISPAN_SERVER_URL:PORT>
    #cache_manager : <CACHE MANAGER> # Optional
  
#ceph:
    #endpoint: <ENDPOINT_URL>
    #access_key: <ACCESS_KEY>
    #secret_key: <ACCESS_KEY>
    
