pywren: 
    storage_bucket: <BUCKET_NAME>
    #storage_prefix: pywren.jobs
    #storage_backend: ibm_cos
    #compute_backend: ibm_cf
    #rabbitmq_monitor: <True/False>
    #data_cleaner: <True/False>
    #runtime :
    #runtime_timeout: 600000     # Default timeout
    #runtime_memory: 256         # Default memory
    #invocation_retry: <True/False>
    #retry_sleeps: [1, 5, 10, 20, 30]
    #retries: 5

#ibm:
#    iam_api_key: <IAM KEY>

ibm_cf:
    endpoint    : <REGION_ENDPOINT>
    namespace   : <NAMESPACE>
    api_key     : <API_KEY>

ibm_cos:
    endpoint    : <REGION_ENDPOINT>
    api_key     : <API_KEY>
    #access_key : <ACCESS_KEY>  # Optional
    #secret_key : <SECRET_KEY>  # Optional

#rabbitmq:
    #amqp_url   : <RABBIT_AMQP_URL>  # amqp://

#knative:
#   endpoint    : <ISTIO_INGRESS_ENDPOINT>
#   docker_user : <DOCKER_HUB_USERNAME>
#   docker_token: <DOCKER_HUB_TOKEN>

#swift:
    #auth_url   : <SWIFT_AUTH_URL>
    #region     : <SWIFT_REGION>
    #user_id    : <SWIFT_USER_ID>
    #project_id : <SWIFT_PROJECT_ID>
    #password   : <SWIFT_PASSWORD>
