name: "on-pull-request"

on:
  pull_request:
    branches:
      - master
    paths:
      - 'lithops/**'
  
  workflow_dispatch: 
  # this allows to run the workflow manually through the github dashboard

jobs:

  localhost_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Lithops repository
        uses: actions/checkout@v3

      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Lithops
        run: |
          pip3 install -U .[tests]

      - name: Run Lithops tests
        run: |
          cd lithops/tests
          pytest -o log_cli=true --log-cli-level=DEBUG --backend localhost --storage localhost

  python_linting:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Lithops repository
        uses: actions/checkout@v3

      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -U flake8

      - name: Install Lithops
        run: |
          pip3 install -U .
      
      - name: Lint with flake8
        run: |
          flake8 lithops --count --max-line-length=180 --statistics --ignore W605
