name: "Push or PR git-action "

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/**.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**/**.md'


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Clone Lithops repository
        uses: actions/checkout@v2
      - name: Install Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
#      - name: Install dependencies
#        run: |
#          python3 setup.py develop
      - name: install secrets in lithops config
        run: python3 ./lithops/scripts/config_fill_secrets.py "${{ secrets.IAMAPIKEY }}" "${{ secrets.COS_API_KEY }}"
      - name: build new runtime
        run: ls -la
        shell: bash
#      - name: Run Python tests
#        run: python3 -m lithops.tests.tests_main -t test_map -c lithops/tests/lithops_config.yaml
